defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: pages_demo_development

test:
  <<: *defaults
  database: pages_demo_test

# set these environment variables on your prod server
production:
  url: <%= ENV['MONGOHQ_URL'] %>
